name: Deploy using AWS SSM Send-Command

on:
  push:
    branches: [ main, Development ]
  pull_request:
    branches: [ main, Development ]

jobs:
  start:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: AWS SSM Send Command
        uses: aws-ssm-send-command@1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1
          instance-ids: i-0c70571cb842f8c67
          comment: Deploy the main branch
          working-directory: /home/ubuntu/bsc23grassroots/Source
          command: /bin/sh ./deploy.sh
